# -*- coding: utf-8 -*-
"""data_fetcher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SCmUNhJH6tviM5-fiOmXGrM5f0eC2hHN
"""

import pandas as pd
import numpy as np

df = pd.read_excel("train(1).xlsx")
print("Initial shape:", df.shape)

# Drop missing values
df = df.dropna()

# Remove non-positive prices
df = df[df["price"] > 0]

print("After cleaning:", df.shape)

df = df.drop(columns=["id", "zipcode"], errors="ignore")
df["date"] = pd.to_datetime(df["date"])

df["year_sold"] = df["date"].dt.year
df["month_sold"] = df["date"].dt.month

df = df.drop(columns=["date"])
df["renovated_flag"] = (df["yr_renovated"] > 0).astype(int)

df["house_age"] = df["year_sold"] - df["yr_built"]
# log scale (VERY IMPORTANT)
df["log_sqft_living"] = np.log1p(df["sqft_living"])

# ratios
df["sqft_per_bed"] = df["sqft_living"] / (df["bedrooms"] + 1)
df["bath_per_bed"] = df["bathrooms"] / (df["bedrooms"] + 1)

# structure ratios
df["above_ratio"] = df["sqft_above"] / (df["sqft_living"] + 1)
lat_center = df["lat"].mean()
lon_center = df["long"].mean()

df["dist_center"] = np.sqrt(
    (df["lat"] - lat_center)**2 +
    (df["long"] - lon_center)**2
)

df["lat_long"] = df["lat"] * df["long"]
df["log_price"] = np.log(df["price"])

drop_cols = [
    "price",
    "sqft_living",
    "sqft_above",
    "yr_built",
    "yr_renovated"
]

df = df.drop(columns=drop_cols)

# ===============================
# REQUIRED PACKAGES
# ===============================
# pip install requests pillow tqdm pandas

import os
import math
import requests
import pandas as pd
from PIL import Image
from io import BytesIO
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm import tqdm

# ===============================
# CONFIG
# ===============================
IMAGE_DIR = "sat_images_esri"
LOG_FILE = "image_download_log.csv"

ZOOM_LEVEL = 18
TILE_GRID = 3          # 3×3 tiles
OUT_SIZE = 224
MAX_WORKERS = 5        # DO NOT exceed 6 (ESRI throttles)

os.makedirs(IMAGE_DIR, exist_ok=True)

# ===============================
# UTILS
# ===============================
def latlon_to_tile(lat, lon, zoom):
    lat_rad = math.radians(lat)
    n = 2.0 ** zoom

    x = int((lon + 180.0) / 360.0 * n)
    y = int(
        (1.0 - math.log(math.tan(lat_rad) + 1 / math.cos(lat_rad)) / math.pi)
        / 2.0 * n
    )
    return x, y


def fetch_esri_tile(z, x, y):
    url = (
        "https://services.arcgisonline.com/ArcGIS/rest/services/"
        f"World_Imagery/MapServer/tile/{z}/{y}/{x}"
    )
    r = requests.get(url, timeout=10)
    r.raise_for_status()
    return Image.open(BytesIO(r.content)).convert("RGB")


def fetch_esri_stitched(lat, lon):
    cx, cy = latlon_to_tile(lat, lon, ZOOM_LEVEL)
    half = TILE_GRID // 2

    tiles = []
    for dy in range(-half, half + 1):
        row = []
        for dx in range(-half, half + 1):
            tile = fetch_esri_tile(ZOOM_LEVEL, cx + dx, cy + dy)
            row.append(tile)
        tiles.append(row)

    tile_size = tiles[0][0].size[0]
    full_size = tile_size * TILE_GRID
    stitched = Image.new("RGB", (full_size, full_size))

    for r in range(TILE_GRID):
        for c in range(TILE_GRID):
            stitched.paste(
                tiles[r][c],
                (c * tile_size, r * tile_size)
            )

    return stitched.resize((OUT_SIZE, OUT_SIZE))


# ===============================
# ROW PROCESSOR
# ===============================
def process_row(row):
    row_id = row["row_id"]
    out_path = os.path.join(IMAGE_DIR, f"{row_id}.png")

    if os.path.exists(out_path):
        return row_id, "skipped"

    try:
        img = fetch_esri_stitched(row["lat"], row["long"])
        img.save(out_path, format="PNG")
        return row_id, "saved"
    except Exception as e:
        return row_id, f"error: {str(e)}"


# ===============================
# MAIN
# ===============================
def main(df):
    # 🔒 Freeze row ↔ image mapping
    df = df.reset_index(drop=True)
    df["row_id"] = df.index

    print(f"Downloading {len(df)} images using {MAX_WORKERS} workers\n")

    results = []

    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        futures = [
            executor.submit(process_row, row)
            for _, row in df.iterrows()
        ]

        for f in tqdm(as_completed(futures), total=len(futures)):
            results.append(f.result())

    # Save audit log
    log_df = pd.DataFrame(results, columns=["row_id", "status"])
    log_df.to_csv(LOG_FILE, index=False)

    print("\nDownload completed.")
    print(f"Log saved to: {LOG_FILE}")
    print(f"Images saved in: {IMAGE_DIR}")


# ===============================
# RUN
# ===============================
main(df)

pip install torch torchvision tqdm pillow numpy pandas

key=lambda x: int(float(x.replace(".png", "")))

import os
import torch
import pandas as pd
import numpy as np
from PIL import Image
from tqdm import tqdm
from torchvision import models, transforms
from torchvision.models import ResNet50_Weights

# ===============================
# CONFIG
# ===============================
IMAGE_DIR = "sat_images_esri"
OUTPUT_FILE = "cnn_embeddings.npy"
META_FILE = "cnn_embedding_index.csv"
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# ===============================
# MODEL
# ===============================
model = models.resnet50(weights=ResNet50_Weights.DEFAULT)
model.fc = torch.nn.Identity()
model = model.to(DEVICE)
model.eval()

# ===============================
# TRANSFORMS (FIXED)
# ===============================
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],   # ImageNet mean
        std=[0.229, 0.224, 0.225]     # ImageNet std
    )
])

# ===============================
# LOAD IMAGE LIST
# ===============================
image_files = sorted(
    [f for f in os.listdir(IMAGE_DIR) if f.endswith(".png")],
    key=lambda x: int(float(x.replace(".png", "")))
)

row_ids = []
embeddings = []

# ===============================
# EMBEDDING EXTRACTION
# ===============================
with torch.no_grad():
    for img_name in tqdm(image_files):
        row_id = int(float(img_name.replace(".png", "")))
        img_path = os.path.join(IMAGE_DIR, img_name)

        img = Image.open(img_path).convert("RGB")
        img = transform(img).unsqueeze(0).to(DEVICE)

        emb = model(img).cpu().numpy()[0]
        embeddings.append(emb)
        row_ids.append(row_id)

# ===============================
# SAVE
# ===============================
embeddings = np.vstack(embeddings)
np.save(OUTPUT_FILE, embeddings)
pd.DataFrame({"row_id": row_ids}).to_csv(META_FILE, index=False)

print("✅ Embeddings generated")
print("Shape:", embeddings.shape)  # (N, 2048)

import numpy as np
import pandas as pd

# ===============================
# SAVE EMBEDDINGS
# ===============================
np.save("cnn_embeddings.npy", embeddings)  # shape: (N, 2048)

# Save row_id mapping
pd.DataFrame({
    "row_id": row_ids
}).to_csv("cnn_embedding_index.csv", index=False)

print("✅ Embeddings saved")
print("File: cnn_embeddings.npy")
print("File: cnn_embedding_index.csv")


# ============================================================
# NOTE: Applying the Same Pipeline to Test Data
# ============================================================
# This entire data fetching and embedding pipeline can be
# applied to the test dataset by simply:
#
# 1. Replacing the input file (e.g., train(1).xlsx → test2.xlsx)
# 2. Running the same preprocessing and feature engineering
# 3. Generating satellite images using lat/long coordinates
# 4. Extracting CNN embeddings with the same frozen ResNet50
#
# IMPORTANT:
# - The same preprocessing logic MUST be used for train and test
# - The row_id ↔ image mapping must remain consistent
# - No refitting of PCA or models should be done on test data
#
# This ensures fair evaluation and prevents data leakage.
# ===========================================================

